### ISSUE TITLE
Сделать страничку на https://pages.github.com/ для этого репозитория

### ISSUE THREAD

**Issue by ASDjonok** [ASDjonok/ASDjonok.github.io#6]
Пример: http://catherinedeneuve.github.io/OOP/

**Comment by SladkiyKeks** [comment]
На страничку можно перейти по ссылке:
https://asdjonok.github.io/version%202/

**Comment by ASDjonok** [comment]
:) Спасибо. Уже знаю. Специально переименовал репозиторий.

**Comment by ASDjonok** [comment]
Для отображения фронтенд-страницы пришлось переименовать репозиторий на "ASDjonok.github.io". 
Ссылка на страницу первой версии вёрстки: https://asdjonok.github.io/version%201/
Ссылка на страницу второй версии вёрстки: https://asdjonok.github.io/version%202/
